name: validate-g8
run-name: Validate g8 template
on:
  push:
  pull_request:
    types: [opened, review_requested]

jobs:
  validate-g8:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Setup mill
        uses: zhutmost/setup-mill@main
        with:
          mill-version: 0.11.12
      - name: Validate
        run: mill g8.validate
